---
- name: Test connectivity to Windows Server using SSH
  hosts: Server
  gather_facts: no

  tasks:
    - name: Check basic connectivity (PowerShell ping)
      ansible.builtin.raw: "Test-Connection -Count 1 localhost | Select-Object -ExpandProperty Status"
      register: ping_result
      changed_when: false

    - name: Show ping result
      ansible.builtin.debug:
        msg: "Ping result: {{ ping_result.stdout | trim }}"
