---
- name: Test connectivity to Windows Server using SSH
  hosts: Server
  gather_facts: no

  tasks:
    - name: Test PowerShell execution
      ansible.windows.win_shell: "Write-Output 'Hello from PowerShell over SSH'"
      register: output

    - name: Show result
      ansible.builtin.debug:
        var: output.stdout
