---
- name: Test connectivity to Windows Server using SSH
  hosts: Server
  gather_facts: no

  tasks:
    - name: Verify connection with PowerShell
      ansible.builtin.raw: "Write-Output 'Hello from PowerShell on Windows via SSH'"
      register: result

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout
